### ISSUE TITLE
Support negation operator in jsExternalModules and jsIgnoredModules

### ISSUE THREAD

**Issue by eduardoboucas** [netlify/zip-it-and-ship-it#381]
**- Do you want to request a _feature_ or report a _bug_?**

A feature 🚀 

**- What is the expected behavior?**

The `jsExternalModules` and `jsIgnoredModules` should support a negation operator (`!`), allowing a module to be excluded from the list.

Example:

```toml
# All functions have "module-one" and "module-two" as externals
[functions]
  js_external_modules = ["module-one", "module-two"]

# ... except for my-function, which has "module-one" and "module-three" (not "module-two")
[functions.my-function]
  js_external_modules = ["module-three", "!module-two"]
```
